<?php require './templates/header.phtml'; ?>

<div class="container-jugadores">
    <h1>Equipos del fútbol europeo</h1>
    <?php foreach ($equipos as $equipo) : ?>
        <div class="card">
            <div class="jugador-info">
                <h2><?= $equipo->equipo . ' ' . $equipo->liga . ' ' . $equipo->pais ?></h2>
                <a href="verjugadores/<?= $equipo->id ?>" class="d-flex justify-content-center btn btn-outline-primary">Ver más</a>


            </div>
        </div>
    <?php endforeach ?>
</div>



    


