<?php require 'templates/header.phtml' ?>
<?php require 'templates/form_equipos.phtml' ?>



<h1>equipos del fulvo europeo</h1>
    <div class="container-jugadores">
    <?php foreach ($equipos as $equipo) : ?>
    <div class="card">
      
        <div class="jugador-info">
            <h2><?= $equipo->equipo . ' ' . $equipo->liga . ' ' . $equipo->pais ?></h2>
            
        </div>
        <a href="eliminarequipo/<?= $equipo->id ?>" class="delete-button">Borrar</a>

        <a href="editar/<?= $equipo->id ?>" class="edit-button">Editar</a>

    </div>
<?php endforeach ?>

    </div>

<?php require 'templates/footer.phtml' ?>