<!-- formulario de alta de tarea -->
<form action="agregar" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="nombre" type="text" class="form-control">
                <label>Apellido</label>
                <input required name="apellido" type="text" class="form-control">
                <div class="col-3">
                    
            <div class="form-group">
                <label>Equipo</label>
                <select required name="id_equipo" class="form-control">
                    <option value="1">Manchester City</option>
                    <option value="2">Lille Olympique</option>
                    <option value="3">Inter de Milán</option>
                    <option value="4">Napoli</option>
                    <option value="5">PSG</option>
                    <option value="6">La Roma</option>
                    <option value="7">Bayern de Múnich</option>
                    <option value="8">Ittihad FC</option>
                    <option value="9">Olympique de Lyon</option>
                    <option value="10">Barcelona</option>
                </select>
            </div>
        </div>
              
            </div>
        </div>
    </div>


    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    <h1>Top 10 goleadores del fulvo europeo</h1>
</form>