
<!-- formulario de equipos -->
<section id="equipos-form">
<form action="agregarequipos" method="POST" class="my-4">

    
            <div class="form-group">
                <label>equipo</label>
                <input required name="equipo" type="text" class="form-control">
                <label>liga</label>
                <input required name="liga" type="text" class="form-control">
                <label>pais</label>
                <input required name="pais" type="text" class="form-control">     
            
       
              
                <button type="submit" class="btn btn-primary mt-2">Guardar</button>
                
    </div>
</form>
</section>