<?php require 'templates/header.phtml' ?>

<h1>Top 10 goleadores del fulvo europeo</h1>
<div class="container-jugadores">
    <?php foreach ($jugadores as $jugador) : ?>
        <div class="card">

        <h2 ><?= $jugador->nombre . ' ' . $jugador->apellido . ' ' . $equipos[$jugador->id_equipo]->equipo ?></h2>
            
        </div>
    <?php endforeach ?>
</div>

<p class="contador-jugadores"><small>Mostrando <?= $count ?> jugadores</small></p>

<?php require 'templates/footer.phtml' ?>