<?php require 'templates/header.phtml' ?>

<?php require 'templates/form_alta.phtml' ?>


<?php
$equipos = array(
    '1' => 'Manchester City',
    '2' => 'Lille Olympique',
    '3' => 'Inter de Milán',
    '4' => 'Napoli',
    '5' => 'PSG',
    '6' => 'La Roma',
    '7' => 'Bayern de Múnich',
    '8' => 'Ittihad FC',
    '9' => 'Olympique de Lyon',
    '10' => 'Barcelona'
);
?>

<ul class="list-group">
<?php foreach($tasks as $task): ?>
    <li class="list-group-item item-task <?php if($task->finalizada): ?> finalizada <?php endif ?>">
        <div>
            <b><?= $task->nombre ?></b>  <b><?= $task->apellido ?></b> <?= $equipos[$task->id_equipo] ?>
        </div>
        <div class="actions">
            <?php if(!$task->finalizada): ?> 
                <a href="finalizar/<?= $task->id ?>" type="button" class='btn btn-success ml-auto'>Finalizar</a> 
            <?php endif ?>
            <a href="eliminar/<?= $task->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> tareas</small></p>


<?php require 'templates/footer.phtml' ?>
